services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python3.10 -m uvicorn api.main:app --reload --host 0.0.0.0 --port 8888
    container_name: fastapi-app
    depends_on:
      db:
        condition: service_started
    ports:
      - published: 8888
        target: 8888
    volumes:
      - type: bind
        source: ./backend
        target: /usr/code/
    working_dir: /usr/code/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev
    container_name: frontend-react
    volumes:
      - type: bind
        source: ./frontend
        target: /usr/frontend
    ports:
      - published: 3000
        target: 3000
    tty: true

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - published: 5432
        target: 5432
    volumes:
      - type: volume
        source: postgres-volume
        target: /var/lib/postgresql/data

volumes:
  postgres-volume:
    name: fastapi-postgresq-sqlalchemy-template
